name: TradeCraft
version: '1.0-SNAPSHOT'
main: dev.tradecraft.tradecraft.TradeCraft
api-version: '1.21'
author: DecDuck
commands:
  authorize:
    description: Authorize a web session with your Minecraft account
    usage: /authorize <code>
    permission: tradecraft.authorize
  createbrand:
    usage: /createbrand
permissions:
  tradecraft.authorize:
    description: Allows user to use /authorize to connect to the web UI
    default: true
  tradecraft.admin:
    description: Allows user to access the admin area on the web UI
    default: false